# .pre-commit-hooks.yaml
-   id: sonar-secrets
    name: Sonar Secrets
    description: "Prevents secrets from being committed to the repository with Sonar's detection engine"
    entry: sonar-secrets
    language: python
    types: [file]
    require_serial: true